name: R CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 'release'

    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'testthat'))"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
        
    - name: Check
      run: R CMD check --no-manual --as-cran

    - name: Upload check results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: rcheck
        path: check/**
